// File was generated by AI

const mongoose = require("mongoose");
const dotenv = require("dotenv");
const { v4: uuidv4 } = require("uuid");
dotenv.config();

// Mongoose models
const User = require("../models/User");
const WebsiteReview = require("../models/WebsiteReview");

// 50 predefined website review comments
const comments = [
  "Loved the quality and fast shipping! Will definitely be coming back for more styles.",
  "Stylish clothes at great prices! My wardrobe has never looked better thanks to Loomhub.",
  "Everything fits perfectly — so happy! It's rare to find such reliable sizing online.",
  "Customer service was top-notch! They responded quickly and solved my issue with ease.",
  "My new favorite place to shop! Every piece feels thoughtfully designed and crafted.",
  "Trendy and super comfortable. It's the perfect combination I didn't know I needed!",
  "Easy checkout and quick delivery. The whole process was smooth and stress-free.",
  "Beautiful fabrics and vibrant colors! They truly stand out compared to other brands.",
  "I always find what I need here. Shopping feels effortless with their great variety.",
  "Excellent value for the money! It's amazing how affordable high quality can be.",
  "True to size and very flattering. I feel so confident every time I wear these clothes.",
  "Can't wait to order again! Their new arrivals section is already calling my name.",
  "Loomhub never disappoints. Every package feels like opening a present to myself.",
  "So many compliments on my outfit! Friends keep asking where I shop now.",
  "Clothes look even better in person! The attention to detail is seriously impressive.",
  "High-quality materials — worth every penny. You can tell these pieces will last a long time.",
  "Fast, easy, and reliable shopping. Honestly one of the best online experiences I've had.",
  "Everything arrived exactly as pictured. It's refreshing when reality matches expectations!",
  "Affordable fashion with premium quality! They’ve really nailed the balance between price and luxury.",
  "Amazing deals and beautiful pieces. I love checking out their sales section for hidden gems.",
  "Such unique and stylish selections! Every collection feels fresh and inspiring.",
  "Perfect for every season! I'm already planning my outfits for summer and fall.",
  "Feels like luxury at a fair price. Finally, style doesn't have to come with a huge price tag.",
  "Highly recommend to all my friends! It's quickly become everyone's go-to shop.",
  "Super soft and comfy fabrics. I could practically live in these pieces all day!",
  "Love the sustainable packaging! It feels good supporting a brand that cares about the planet.",
  "This site makes fashion so easy. It's a real timesaver when I need a quick outfit update.",
  "Impressed with the craftsmanship. Stitching and finishes are better than many big brands.",
  "Customer support was so helpful! Solved my return issue within minutes — no hassle at all.",
  "My closet is full of Loomhub now! Honestly, I barely shop anywhere else anymore.",
  "Fast returns and great support! It’s comforting knowing the return process is painless if needed.",
  "Timeless pieces that last! I know I'll be wearing these clothes for many seasons ahead.",
  "I’m obsessed with the new collection! Every piece just fits my style so perfectly.",
  "Everything matched the photos exactly. No weird surprises when opening the package.",
  "Perfect for casual and formal looks. I love being able to dress things up or down so easily.",
  "Amazing styles for any occasion. Whether it’s work or weekend, Loomhub has me covered.",
  "Best online shopping experience! From browsing to unboxing, everything felt premium.",
  "Found so many wardrobe staples! I’ve never refreshed my closet this easily before.",
  "Lightweight, breathable, and stylish. Perfect for all-day wear, even in warmer weather.",
  "Fashion-forward without breaking the bank. Finally, I can follow trends without overspending!",
  "Will definitely keep shopping here. Can't wait to see what new collections they release next!",
  "Love how easy it is to browse! Their site is intuitive, clean, and fun to use.",
  "Always excited to open my package! It feels like Christmas every single time.",
  "So many options for every style! Whether you like classic or trendy, you’ll find something here.",
  "Great for gifts too! I already picked out a few items for birthdays and holidays.",
  "The quality exceeded my expectations. You don't often get this level of care at these prices.",
  "Fast shipping and beautiful clothes. Exactly the experience I hope for when shopping online.",
  "This site makes me love shopping again! It takes the frustration out of finding cute, comfy outfits.",
  "Every piece feels specially made. It's like each item was designed with real people in mind.",
  "So happy I found Loomhub! Wish I had discovered them sooner — absolutely obsessed now!",
];

// Helper to pick random integer between min and max inclusive
const getRandomRating = () => Math.floor(Math.random() * 3) + 3; // 3, 4, or 5

/**
 * Function to generate 50 unique website reviews
 */
const generateWebsiteReviews = async () => {
  try {
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(process.env.MONGODB_URI, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
    }

    const users = await User.find({});
    if (users.length < 50) {
      throw new Error(
        "Not enough users found in the database to assign reviews."
      );
    }

    // Shuffle users and comments to avoid duplicates
    const shuffledUsers = [...users]
      .sort(() => Math.random() - 0.5)
      .slice(0, 50);
    const shuffledComments = [...comments].sort(() => Math.random() - 0.5);

    const websiteReviews = shuffledUsers.map((user, index) => {
      return {
        user: user._id,
        rating: getRandomRating(),
        comment: shuffledComments[index],
      };
    });

    await WebsiteReview.insertMany(websiteReviews);

    console.log(
      `✅ Successfully created ${websiteReviews.length} website reviews.`
    );
  } catch (error) {
    console.error("❌ Error generating website reviews:", error);
  } finally {
    await mongoose.connection.close();
  }
};

// Run automatically
generateWebsiteReviews();
